### ISSUE TITLE
Explore adding T/R notes to a md file that posts to slack

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/Virtual-Coffee-Bot#16]
Idk of this is doable, but could we have notetakers post to a private GitHub repo instead of slack, and then have a slackbot post those notes? 

That way, we preserve the notes and have them in slack

For red: https://github.com/integrations/slack

Maybe this isn't the best way, but is it a better way _now_? If it requires a bunch of time and effort than probably not.  But wanted to mention it.

**Comment by danieltott** [comment]
OK how about this: a form on the site where they can submit the notes. we can hook it up to slack right away, and we'll still get them stored and i can work on adding them to the repo or somewhere else a bit down the line?

**Comment by BekahHW** [comment]
That works for me.

**Comment by tkshill** [comment]
I like it
