### ISSUE TITLE
Enable Slack Commands Server

### ISSUE THREAD

**Issue by MikeRogers0** [Virtual-Coffee/Virtual-Coffee-Bot#41]
I done this before on https://github.com/Bundlify/Kolab-Slack-Bot - I think it will enable people to create `@bot do something` type stuff for us.

On Heroku I think we can do it via the free tier, but we could also look into setting it up via Vercel or something.

**Comment by danieltott** [comment]
Yeah - if we can run it through Netlify functions, that would be the best!
