### ISSUE TITLE
Investigate using calendar instead of meetingplace api

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/Virtual-Coffee-Bot#6]
I don't want to rely on meetingplace forever for this. Eventually we'll have some sort of calendar we can use, possibly one people can subscribe to.

Possible options:

Use public ical-formatted calendar links. Here's an example calendar:

https://calendar.google.com/calendar/ical/c_69locn61onbjf3ui8b0atnss6g%40group.calendar.google.com/public/basic.ics

I would think this would be pretty straightforward. However, we have a set of events that we don't really want to be public, but we do want posted to the slack. So, another option would be to hook into the google calendar API with credentials and then grab specific calendars from there. This would allow the calendar to remain private, but allow the bot to read from it and display info to slack.

I have no idea how much effort this would entail, but would love to hear thoughts on it.

**Comment by tkshill** [comment]
I too know very little about that but it sounds like a good idea. Meetingplace is fine, but clunky, and it'd be so nice if we had our own calendar that slack members could check out without also needing credentials for meentingplace.io.

Do we just need to set a time to test or is this something Mike might have experience with as well?

**Comment by danieltott** [comment]
I was thinking @MikeRogers0 could (if willing and able) adjust the current bot to try to read from the calendars. Even reading from the public one would probably be an improvement for our slack purposes. Don't want to jump head first into anything, but this could be useful.

The way we actually set up the calendars is another issue, but one we can handle separately - no matter what we put in there, the calendar entries will always have date/time, title, desc, and a url, so that should be enough to feed the bot.

**Comment by MikeRogers0** [comment]
https://developers.google.com/calendar/quickstart/ruby / https://github.com/googleapis/google-api-ruby-client - It looks like there is a Gem which wrappers their API (Though IIRC, Google does charge for usage of the API, but does have a free tier). I think we'd just need to authorise access to the calendar & we'll be good to go.

@danieltott Do you want to give me access to the current calendars?

**Comment by kierblk** [comment]
Does our having Virtual Coffee GSuite give us any advantage here with the pricing/options/etc? 

Totally jumping into the conversation late but curious.
