### ISSUE TITLE
Potential Bot commands

### ISSUE THREAD

**Issue by tkshill** [Virtual-Coffee/Virtual-Coffee-Bot#7]
I'm putting these all as one issue for now. Can break them up later once we decide a schedule, implementation plan, etc.

- [ ] Command to get details of next VC meeting "!nextmeeting"
- [ ] Command to get link to brownbag calender
- [ ] Command to get link to brownbag signup form
- [ ] Make sure bot can still post in #announcements if we lock it down
- [ ] Automatic welcome to new members with link to resources, coc, etc.

**Comment by danieltott** [comment]
> Ability to disallow posting in announcements channel

@tkshill what does that mean?

**Comment by tkshill** [comment]
Yeah, I said that weird. I mean that the announcements channel should be like, read only. I'm not sure how we implement that but like, the bot should be able to post in it, and like some official group, but not everyone?

**Comment by MikeRogers0** [comment]
❤️ All of these. Previously when I made a [Slack bot](https://github.com/Bundlify/Kolab-Slack-Bot/blob/master/kolab-slack-bot/commands/joke.rb) we did have to have a server running to listen for when a command was requested. I'll have an investigation as to if there is a better approach available :)

**Comment by danieltott** [comment]
I’d imagine we could use netlify functions for this

**Comment by MikeRogers0** [comment]
https://api.slack.com/events-api#subscriptions - I think that should be possible :D I'll have a mess around over the next week :D

**Comment by MikeRogers0** [comment]
Another bot command which could be cool `@VirtualCoffee.io save-that` - For when we want to save a link/post somewhere outside of slack.
